### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by Osamu01** [rugg0064/random-hopper#2]
Plugin stopped working for me. Simply can't use the hotkeys and it's not loading.

**Comment by matthew-blueamaryllisconsulting** [comment]
When it isn't working, do you still have a sidebar panel, or is that missing?
There is an active bug where the sidebar doesn't appear, meaning the entire plugin is inactive. There is a PR to fix that issue in particular.

**Comment by rugg0064** [comment]
When it isn't working, do you still have a sidebar panel, or is that missing?
There is an active bug where the sidebar doesn't appear, meaning the entire plugin is inactive. There is a PR to fix that issue in particular.

**Comment by Osamu01** [comment]
> When it isn't working, do you still have a sidebar panel, or is that missing? There is an active bug where the sidebar doesn't appear, meaning the entire plugin is inactive. There is a PR to fix that issue in particular.

Yes, the sidebar doesn't appear. The console logs print a bunch of stuff about the UI failing and it occasionally chooses when to work. How long will I have to wait for a fix?

**Comment by rugg0064** [comment]
> How long will I have to wait for a fix to push to runelite?

It's been submitted for over a week which is usually how long it takes for them to approve changes. Hopefully some of the runelite guys get around to it soon.

**Comment by Osamu01** [comment]
> > How long will I have to wait for a fix to push to runelite?
> 
> It's been submitted for over a week which is usually how long it takes for them to approve changes. Hopefully some of the runelite guys get around to it soon.

Thank you! Great plugin btw. I found it after a PKER using the default World Hopper(next-previous hotkeys) followed me through like 2-3 worlds before I luckily caught a logout lol.

**Comment by rugg0064** [comment]
The update was merged into plugin hub. Should be working now.
