### ISSUE TITLE
Hopper Causing Crash Upon Hopping to Mobile World

### ISSUE THREAD

**Issue by Just1issue** [rugg0064/random-hopper#3]
The Mobile UI Beta worlds are a possible hop point. As of today's update, if it hits one of these worlds, it forces a soft or hard crash of Runelite. Means that there is a small chance that, with each random hop, that the client will crash. These are worlds 585-589.

**Comment by Just1issue** [comment]
> Will replicate and try to fix asap

Repro:

From login screen, click "Random Hop" button until it lands on one of the worlds. Issue should immediately happen. 

Sub: P2P
PVP: Never
High Risk: Never
Skill Total: Sometimes
Target World: Never
Seed: none
Region: All
World Type: Normal

Instance 1: Hit 587. Crash did not occur. 
Instance 2: Hit 586. Crash did not occur. 
Instance 3: Hit 587. Crash did not occur.

Something to note, those servers are back online, so that is likely where the difference is now. It'd probably be best to remove the mobile beta worlds from the "Normal" world set.

**Comment by rugg0064** [comment]
PR in plugin hub should fix this
https://github.com/runelite/plugin-hub/pull/5006

**Comment by rugg0064** [comment]
Fix should be merged in. Re-open issue if it didn't actually fix please.
