### ISSUE TITLE
"Subscription" field resets/defaults to P2P on every launch of RuneLite

### ISSUE THREAD

**Issue by DigitalNTT-Soul** [rugg0064/random-hopper#4]
Title pretty much sums it up. Every time I start up RuneLite, the Subscription field defaults back to P2P evem if I changed it during my previous session and closed RuneLite while the setting was something different. This occurs regardless of whether I set it to F2P or Either. I haven't tried messing with any of that menu's other options, but if there's an error causing those settings to not be saved properly, I figured I would bring it to your attention in the hopes that it gets fixed for those of us who aren't members or are doing non-member challenges.

**Comment by rugg0064** [comment]
Sorry for the 1 year delay.. Hopefully adding this feature will still benefit someone out there.
Merged into dev in cb761ae4c7ebdd5ff74e9bb7a340d462751d9708. It will be available in the next plugin hub release.
