### ISSUE TITLE
Spam clicking the hop random keybind will make you insta hop again on the next world

### ISSUE THREAD

**Issue by pwatts6060** [rugg0064/random-hopper#6]
Say I'm on W360 and start spam clicking the hop random key to hop worlds, it will hop me to the next random world say 375, and as soon as I login, it will hop me again to another random world. Once it starts a hop it should cancel any other hop attempts until I'm logged in on 375.

**Comment by rugg0064** [comment]
I added a check to the hopping functionality that blocks it during the hopping and loading game states. This should resolve the issue. I will submit this to the plugin hub soon.
